@startuml Usecase - Ban Chủ Nhiệm (BCN)
left to right direction
skinparam actorStyle awesome

actor "Ban Chủ Nhiệm" as BCN

rectangle "Hệ thống Quản lý Thực tập" {
  usecase "Quản lý môn thực tập" as UC_BCN_1
  usecase "Quản lý trang khoa" as UC_BCN_2
  usecase "Quản lý yêu cầu" as UC_BCN_3
  usecase "Quản lý báo cáo" as UC_BCN_4
  usecase "Duyệt điểm thực tập" as UC_BCN_5
  usecase "Chat hỗ trợ" as UC_BCN_6
  usecase "Xem thông báo" as UC_BCN_7
}

BCN --> UC_BCN_1
BCN --> UC_BCN_2
BCN --> UC_BCN_3
BCN --> UC_BCN_4
BCN --> UC_BCN_5
BCN --> UC_BCN_6
BCN --> UC_BCN_7

@enduml
