@startuml Usecase - Phòng Đào Tạo (PDT)
left to right direction
skinparam actorStyle awesome

actor "Phòng Đào Tạo" as PDT

rectangle "Hệ thống Quản lý Thực tập" {
  usecase "Quản lý tài khoản" as UC_PDT_1
  usecase "Quản lý môn thực tập" as UC_PDT_2
  usecase "Quản lý tổng kết" as UC_PDT_3
  usecase "Thống kê điểm" as UC_PDT_4
  usecase "Chat hỗ trợ" as UC_PDT_5
  usecase "Xem thông báo" as UC_PDT_6
}

PDT --> UC_PDT_1
PDT --> UC_PDT_2
PDT --> UC_PDT_3
PDT --> UC_PDT_4
PDT --> UC_PDT_5
PDT --> UC_PDT_6

@enduml
