@startuml Usecase - Sinh Viên (SV)
left to right direction
skinparam actorStyle awesome

actor "Sinh Viên" as SV

rectangle "Hệ thống Quản lý Thực tập" {
  usecase "Xem tài liệu khoa" as UC_SV_1
  usecase "Xem tài liệu gv" as UC_SV_2
  usecase "Tiến độ thực tập" as UC_SV_3
  usecase "Chat hỗ trợ" as UC_SV_4
  usecase "Đăng ký môn" as UC_SV_5
  usecase "Xem thông báo" as UC_SV_6
}

SV --> UC_SV_1
SV --> UC_SV_2
SV --> UC_SV_3
SV --> UC_SV_4
SV --> UC_SV_5
SV --> UC_SV_6

@enduml
